default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 19061992
  host: localhost

development:
  <<: *default
  database: YaroBDS_development

test:
  <<: *default
  database: YaroBDS_test

production:
  <<: *default
  database: YaroBDS_production
